scss_files: '**/*.scss'
plugin_directories: ['.scss-linters']

# List of gem names to load custom linters from (make sure they are already
# installed)
plugin_gems: []

# Default severity of all linters.
severity: warning

linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BemDepth:
    enabled: true
    max_elements: 2
    severity: error

  BorderZero:
    enabled: true
    convention: zero # or `none`
    severity: error

  ChainedClasses:
    enabled: true
    severity: error

  ColorKeyword:
    enabled: true
    severity: error

  ColorVariable:
    enabled: true
    severity: error

  Comment:
    enabled: true
    style: silent
    severity: error

  DebugStatement:
    enabled: true
    severity: error

  DeclarationOrder:
    enabled: true

  DisableLinterReason:
    enabled: false

  DuplicateProperty:
    enabled: true
    severity: error

  ElsePlacement:
    enabled: true
    style: same_line # or 'new_line'

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  ExtendDirective:
    enabled: true
    severity: error

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: long # or 'long'
    severity: error

  HexNotation:
    enabled: true
    style: uppercase # or 'uppercase'
    severity: error

  HexValidation:
    enabled: true

  IdSelector:
    enabled: true

  ImportantRule:
    enabled: true

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false
    serverity: error

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space # or 'tab'
    width: 2

  LeadingZero:
    enabled: true
    style: include_zero # or 'exclude_zero'

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: true
    allow_leading_underscore: true
    convention: hyphenated_lowercase # or 'camel_case', or 'snake_case', or a regex pattern

  NestingDepth:
    enabled: true
    max_depth: 3
    ignore_parent_selectors: false

  PlaceholderInExtend:
    enabled: false

  PrivateNamingConvention:
    enabled: false
    prefix: _

  PropertyCount:
    enabled: true
    include_nested: false
    max_properties: 10

  PropertySortOrder:
    enabled: true
    severity: error
    ignore_unspecified: false
    min_properties: 2
    separate_groups: false
    order:
      # SMACSS: https://smacss.com
      # Positioning
      - 'display'
      - 'position'
      - 'top'
      - 'right'
      - 'bottom'
      - 'left'

      # Box model
      - 'flex'
      - 'flex-basis'
      - 'flex-direction'
      - 'flex-flow'
      - 'flex-grow'
      - 'flex-shrink'
      - 'flex-wrap'
      - 'align-content'
      - 'align-items'
      - 'align-self'
      - 'justify-content'
      - 'order'
      - 'width'
      - 'min-width'
      - 'max-width'
      - 'height'
      - 'min-height'
      - 'max-height'
      - 'margin'
      - 'margin-top'
      - 'margin-right'
      - 'margin-bottom'
      - 'margin-left'
      - 'padding'
      - 'padding-top'
      - 'padding-right'
      - 'padding-bottom'
      - 'padding-left'
      - 'float'
      - 'clear'
      - 'columns'
      - 'column-gap'
      - 'column-fill'
      - 'column-rule'
      - 'column-span'
      - 'column-count'
      - 'column-width'
      - 'transform'
      - 'transform-box'
      - 'transform-origin'
      - 'transform-style'
      - 'transition'
      - 'transition-delay'
      - 'transition-duration'
      - 'transition-property'
      - 'transition-timing-function'

      # Border
      - 'border'
      - 'border-top'
      - 'border-right'
      - 'border-bottom'
      - 'border-left'
      - 'border-width'
      - 'border-top-width'
      - 'border-right-width'
      - 'border-bottom-width'
      - 'border-left-width'
      - 'border-style'
      - 'border-top-style'
      - 'border-right-style'
      - 'border-bottom-style'
      - 'border-left-style'
      - 'border-radius'
      - 'border-top-left-radius'
      - 'border-top-right-radius'
      - 'border-bottom-left-radius'
      - 'border-bottom-right-radius'
      - 'border-color'
      - 'border-top-color'
      - 'border-right-color'
      - 'border-bottom-color'
      - 'border-left-color'
      - 'outline'
      - 'outline-color'
      - 'outline-offset'
      - 'outline-style'
      - 'outline-width'

      # Background
      - 'background'
      - 'background-attachment'
      - 'background-clip'
      - 'background-color'
      - 'background-image'
      - 'background-repeat'
      - 'background-position'
      - 'background-size'

      # Typographic
      - 'color'
      - 'font'
      - 'font-family'
      - 'font-size'
      - 'font-smoothing'
      - 'font-style'
      - 'font-variant'
      - 'font-weight'
      - 'letter-spacing'
      - 'line-height'
      - 'list-style'
      - 'text-align'
      - 'text-decoration'
      - 'text-indent'
      - 'text-overflow'
      - 'text-rendering'
      - 'text-shadow'
      - 'text-transform'
      - 'text-wrap'
      - 'white-space'
      - 'word-spacing'

      # Misc
      - 'border-collapse'
      - 'border-spacing'
      - 'box-shadow'
      - 'caption-side'
      - 'content'
      - 'cursor'
      - 'empty-cells'
      - 'opacity'
      - 'overflow'
      - 'quotes'
      - 'speak'
      - 'table-layout'
      - 'vertical-align'
      - 'visibility'
      - 'z-index'

  PropertySpelling:
    enabled: true
    extra_properties: []
    disabled_properties: []
    severity: error

  PropertyUnits:
    enabled: true
    global: [
      'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
      'vh', 'vw', 'vmin', 'vmax',              # Viewport-percentage lengths
      'deg', 'grad', 'rad', 'turn',            # Angle
      'ms', 's',                               # Duration
      'Hz', 'kHz',                             # Frequency
      'dpi', 'dpcm', 'dppx',                   # Resolution
      '%']                                     # Other
    properties: {}

  PseudoElement:
    enabled: true
    severity: error

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: true
    allow_element_with_id: false

  SelectorDepth:
    enabled: true
    max_depth: 3
    severity: error

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM # or 'strict_BEM', or 'hyphenated_BEM', or 'snake_case', or 'camel_case', or a regex pattern

  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2, 3]

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space'

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space', or 'aligned'

  SpaceAfterPropertyName:
    enabled: true

  SpaceAfterVariableColon:
    enabled: false
    style: one_space # or 'no_space', 'at_least_one_space' or 'one_space_or_newline'

  SpaceAfterVariableName:
    enabled: true

  SpaceAroundOperator:
    enabled: true
    style: one_space # or 'at_least_one_space', or 'no_space'

  SpaceBeforeBrace:
    enabled: true
    style: space # or 'new_line'
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes # or single_quotes

  TrailingSemicolon:
    enabled: true
    severity: error

  TrailingWhitespace:
    enabled: true

  TrailingZero:
    enabled: true

  TransitionAll:
    enabled: true
    severity: error

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true
    severity: error

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: true
    severity: error
    properties:
      - color

  VendorPrefix:
    enabled: true
    identifier_list: base
    additional_identifiers: []
    excluded_identifiers: []

  ZeroUnit:
    enabled: true
    severity: error

  Compass::*:
    enabled: false
